[package]
name = "rh-cve-scanner-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.16"
tokio = { version="1.27.0",  features=["full"]}
serde = { version="1.0.160", features=["derive"]}
serde_derive = "1.0.160"
serde_json = "1.0.96"