[package]
name = "rh-cve-scanner-rust"
version = "0.1.0"
edition = "2021"
authors = ["phil@phiroict.co.nz"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.16"
tokio = { version="1.27.0",  features=["full"]}
serde = { version="1.0.160", features=["derive"]}
serde_derive = "1.0.160"
serde_json = "1.0.96"
log = "0.4.17"
simple_logger = "4.1.0"
env_logger = "0.10.0"
uuid =  { version = "1.3.1", features = ["serde", "v4"] }
chrono = "0.4.24"

[dev-dependencies]
ctor = "0.2.0"